### ISSUE TITLE
Metronome stops working when you change to a different tab

### ISSUE THREAD

**Issue by ccampbell** [cwilso/metronome#7]
I suspect this is related to using `requestAnimationFrame`.  

I am aware that `requestAnimationFrame` is preferable to using `setTimeout` or `setInterval`, but I'm curious what you would recommend for making a web audio app where you want playback to continue even if you switch to another tab in the browser.  

It seems more suited to games (as its name implies) where if you leave the tab there is no need to redraw the page cause you can't see it anymore.  Maybe we need a `requestAudioFrame`?

I also am not sure if this is something specific to my computer and how Chrome optimizes repainting or if it is a more general issue.

Thanks.

**Comment by cwilso** [comment]
No, with https://github.com/cwilso/metronome/commit/7b78d49d297107bec2c10803ee2702f5b4e9e3cc (checked in five months ago) this should not be a problem.  requestAnimationFrame is ONLY used in the current code for drawing purposes, not for audio scheduling.

We don't need a "requestAudioFrame" - we need a way to get setTimeout/setInterval to not be throttled to 1Hz when the tab is not in the foreground.  It turns out you can do that, in a Worker thread, anyway.

**Comment by ccampbell** [comment]
Oh that's awesome. I didn't know about that! Sorry for the confusion.
